timeout: 3000s
options:
  machineType: 'N1_HIGHCPU_8'
steps:

  - name: 'gcr.io/jll-docker-repo/get-npmrc'
    id: Get npmrc

  - name: 'gcr.io/jll-docker-repo/docker-node:12.14.1-6.13.4'
    id: npm install
    args: ['install']

  - name: 'gcr.io/jll-docker-repo/docker-node:12.14.1-6.13.4'
    id: typescript
    args: ['run', 'build']


#  - name: 'gcr.io/jll-docker-repo/docker-node:12.14.1-6.13.4'
#    id: npm test
#    args: ['test']

